// REGION
export const ADD_REGION_START = 'ADD_REGION_START'
export const ADD_REGION_SUCCESS = 'ADD_REGION_SUCCESS'
export const ADD_REGION_FAIL = 'ADD_REGION_FAIL'

export const GET_REGION_START = 'GET_REGION_START'
export const GET_REGION_SUCCESS = 'GET_REGION_SUCCESS'
export const GET_REGION_FAIL = 'GET_REGION_FAIL'

// NEWSLETTER
export const GET_NEWSLETTER_START = 'GET_NEWSLETTER_START'
export const GET_NEWSLETTER_SUCCESS = 'GET_NEWSLETTER_SUCCESS'
export const GET_NEWSLETTER_FAIL = 'GET_NEWSLETTER_FAIL'

// FACILITY
export const GET_FACILITY_START = 'GET_FACILITY_START'
export const GET_FACILITY_SUCCESS = 'GET_FACILITY_SUCCESS'
export const GET_FACILITY_FAIL = 'GET_FACILITY_FAIL'

// TEAM
export const GET_TEAM_START = 'GET_TEAM_START'
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS'
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL'

// TYPE
export const GET_TYPE_START = 'GET_TYPE_START'
export const GET_TYPE_SUCCESS = 'GET_TYPE_SUCCESS'
export const GET_TYPE_FAIL = 'GET_TYPE_FAIL'

// PROPERTY
export const GET_PROPERTY_START = 'GET_PROPERTY_START'
export const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS'
export const GET_PROPERTY_FAIL = 'GET_PROPERTY_FAIL'

// AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GET_USER = "GET_USER";

export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL'

// DASHBOARD
export const GET_TOTAL_VISITOR = 'GET_TOTAL_VISITOR'
export const GET_VISITOR_PROPERTIES = 'GET_VISITOR_PROPERTIES'
export const GET_LOVED_PROPERTIES = 'GET_LOVED_PROPERTIES'
