version: '3.8'
services: 
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "192.168.18.95:8000:80"
    depends_on:
      - frontend
      - dashboard
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "/app/.next"
      - "./dashboard:/app"
  frontend:
    build:
      context: ./home
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "/app/.next"
      - "./home:/app"
