//AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const GET_USER = "GET_USER";

//REGION
export const GET_REGION_START = 'GET_REGION_START'
export const GET_REGION_SUCCESS = 'GET_REGION_SUCCESS'
export const GET_REGION_FAIL = 'GET_REGION_FAIL'

//PROPERTY
export const GET_PROPERTY_START = 'GET_PROPERTY_START'
export const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS'
export const GET_PROPERTY_FAIL = 'GET_PROPERTY_FAIL'

export const GET_PROPERTY_SALE = 'GET_PROPERTY_SALE'
export const GET_PROPERTY_RENT = 'GET_PROPERTY_RENT'
export const GET_PROPERTY_LAND = 'GET_PROPERTY_LAND'

//TEAMS
export const GET_TEAM_START = 'GET_TEAM_START'
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS'
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL'

//TYPE
export const GET_TYPE_START = 'GET_TYPE_START'
export const GET_TYPE_SUCCESS = 'GET_TYPE_SUCCESS'
export const GET_TYPE_FAIL = 'GET_TYPE_FAIL'

//FACILITIES
export const GET_FACILITY_START = 'GET_FACILITY_START'
export const GET_FACILITY_SUCCESS = 'GET_FACILITY_SUCCESS'
export const GET_FACILITY_FAIL = 'GET_FACILITY_FAIL'
