//AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const GET_USER_START = "GET_USER_START";
export const GET_USER = "GET_USER";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_SUBSCRIBE_START = "GET_SUBSCRIBE_START";
export const GET_SUBSCRIBE = "GET_SUBSCRIBE";
export const GET_SUBSCRIBE_FAIL = "GET_SUBSCRIBE_FAIL";

export const GET_TEXT = "GET_TEXT";

//REGION
export const GET_REGION_START = 'GET_REGION_START'
export const GET_REGION_SUCCESS = 'GET_REGION_SUCCESS'
export const GET_REGION_FAIL = 'GET_REGION_FAIL'

export const GET_DATA_REGION_START = 'GET_DATA_REGION_START'
export const GET_DATA_REGION_SUCCESS = 'GET_DATA_REGION_SUCCESS'
export const GET_DATA_REGION_FAIL = 'GET_DATA_REGION_FAIL'

export const SLUG_REGION_START = 'SLUG_REGION_START'
export const SLUG_REGION_SUCCESS = 'SLUG_REGION_SUCCESS'
export const SLUG_REGION_FAIL = 'SLUG_REGION_FAIL'

// NEWSLETTER
export const GET_NEWSLETTER_START = 'GET_NEWSLETTER_START'
export const GET_NEWSLETTER_SUCCESS = 'GET_NEWSLETTER_SUCCESS'
export const GET_NEWSLETTER_FAIL = 'GET_NEWSLETTER_FAIL'

export const SLUG_NEWSLETTER_START = 'SLUG_NEWSLETTER_START'
export const SLUG_NEWSLETTER_SUCCESS = 'SLUG_NEWSLETTER_SUCCESS'
export const SLUG_NEWSLETTER_FAIL = 'SLUG_NEWSLETTER_FAIL'

export const POPULAR_NEWSLETTER_START = 'POPULAR_NEWSLETTER_START'
export const POPULAR_NEWSLETTER_SUCCESS = 'POPULAR_NEWSLETTER_SUCCESS'
export const POPULAR_NEWSLETTER_FAIL = 'POPULAR_NEWSLETTER_FAIL'

export const OLD_NEWSLETTER_START = 'OLD_NEWSLETTER_START'
export const OLD_NEWSLETTER_SUCCESS = 'OLD_NEWSLETTER_SUCCESS'
export const OLD_NEWSLETTER_FAIL = 'OLD_NEWSLETTER_FAIL'

export const GET_TITLE_START = 'GET_TITLE_START'
export const GET_TITLE_SUCCESS = 'GET_TITLE_SUCCESS'
export const GET_TITLE_FAIL = 'GET_TITLE_FAIL'

//PROPERTY
export const GET_PROPERTY_START = 'GET_PROPERTY_START'
export const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS'
export const GET_PROPERTY_FAIL = 'GET_PROPERTY_FAIL'

export const SLUG_PROPERTY_START = 'SLUG_PROPERTY_START'
export const SLUG_PROPERTY_SUCCESS = 'SLUG_PROPERTY_SUCCESS'
export const SLUG_PROPERTY_FAIL = 'SLUG_PROPERTY_FAIL'

export const GET_PROPERTY_SALE = 'GET_PROPERTY_SALE'
export const GET_PROPERTY_RENT = 'GET_PROPERTY_RENT'
export const GET_PROPERTY_LAND = 'GET_PROPERTY_LAND'

export const LOVE_PROPERTY_START = 'LOVE_PROPERTY_START'
export const LOVE_PROPERTY_SUCCESS = 'LOVE_PROPERTY_SUCCESS'
export const LOVE_PROPERTY_FAIL = 'LOVE_PROPERTY_FAIL'

export const UNLOVE_PROPERTY_START = 'UNLOVE_PROPERTY_START'
export const UNLOVE_PROPERTY_SUCCESS = 'UNLOVE_PROPERTY_SUCCESS'
export const UNLOVE_PROPERTY_FAIL = 'UNLOVE_PROPERTY_FAIL'

export const GET_WISHLIST_START = 'GET_WISHLIST_START'
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS'
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL'

export const GET_LOCATION_START = 'GET_LOCATION_START'
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'
export const GET_LOCATION_FAIL = 'GET_LOCATION_FAIL'

//TEAMS
export const GET_TEAM_START = 'GET_TEAM_START'
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS'
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL'

//TYPE
export const GET_TYPE_START = 'GET_TYPE_START'
export const GET_TYPE_SUCCESS = 'GET_TYPE_SUCCESS'
export const GET_TYPE_FAIL = 'GET_TYPE_FAIL'

//FACILITIES
export const GET_FACILITY_START = 'GET_FACILITY_START'
export const GET_FACILITY_SUCCESS = 'GET_FACILITY_SUCCESS'
export const GET_FACILITY_FAIL = 'GET_FACILITY_FAIL'

//CURRENCY
export const GET_CURRENCY = 'GET_CURRENCY'
